<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateCountriesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('pais', function (Blueprint $table) {
            $table->id();
            $table->string('code', 20);
            $table->string('nombre_pais', 50);
            $table->string('abreviacion', 10);
            $table->string('code_telefono', 20);
			$table->boolean('default')->default(false);
        });
        DB::table('pais')->insert([
          [
          'nombre_pais' =>'Venezuela',
          'abreviacion' =>'',
          'code_telefono' => '+58',
          'code' => '0001',
          'default' => 1,
          ],
          [
          'nombre_pais' =>'Afghanistan ',
          'abreviacion' =>'',
          'code_telefono' => '+93',
          'code' => '0002',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Albania ',
          'abreviacion' =>'',
          'code_telefono' => '+355',
          'code' => '0003',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Algeria ',
          'abreviacion' =>'',
          'code_telefono' => '+213',
          'code' => '0004',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'American Samoa',
          'abreviacion' =>'',
          'code_telefono' => '+1-684',
          'code' => '0005',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Andorra Principality of ',
          'abreviacion' =>'',
          'code_telefono' => '+376',
          'code' => '0006',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Angola',
          'abreviacion' =>'',
          'code_telefono' => '+244',
          'code' => '0007',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Anguilla ',
          'abreviacion' =>'',
          'code_telefono' => '+1-264',
          'code' => '0008',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Antarctica',
          'abreviacion' =>'',
          'code_telefono' => '+672',
          'code' => '0009',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Antigua and Barbuda',
          'abreviacion' =>'',
          'code_telefono' => '+1-268',
          'code' => '0010',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Argentina ',
          'abreviacion' =>'',
          'code_telefono' => '+54',
          'code' => '0011',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Armenia',
          'abreviacion' =>'',
          'code_telefono' => '+374',
          'code' => '0012',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Aruba',
          'abreviacion' =>'',
          'code_telefono' => '+297',
          'code' => '0013',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Australia',
          'abreviacion' =>'',
          'code_telefono' => '+61',
          'code' => '0014',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Austria',
          'abreviacion' =>'',
          'code_telefono' => '+43',
          'code' => '0015',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Azerbaijan',
          'abreviacion' =>'',
          'code_telefono' => '+994',
          'code' => '0016',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Bahamas Commonwealth of The',
          'abreviacion' =>'',
          'code_telefono' => '+1-242',
          'code' => '0017',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Bahrain Kingdom of ',
          'abreviacion' =>'',
          'code_telefono' => '+973',
          'code' => '0018',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Bangladesh',
          'abreviacion' =>'',
          'code_telefono' => '+880',
          'code' => '0019',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Barbados ',
          'abreviacion' =>'',
          'code_telefono' => '+1-246',
          'code' => '0020',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Belarus',
          'abreviacion' =>'',
          'code_telefono' => '+375',
          'code' => '0021',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Belgium ',
          'abreviacion' =>'',
          'code_telefono' => '+32',
          'code' => '0022',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Belize',
          'abreviacion' =>'',
          'code_telefono' => '+501',
          'code' => '0023',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Benin',
          'abreviacion' =>'',
          'code_telefono' => '+229',
          'code' => '0024',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Bermuda ',
          'abreviacion' =>'',
          'code_telefono' => '+1-441',
          'code' => '0025',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Bhutan Kingdom of',
          'abreviacion' =>'',
          'code_telefono' => '+975',
          'code' => '0026',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Bolivia ',
          'abreviacion' =>'',
          'code_telefono' => '+591',
          'code' => '0027',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Bosnia and Herzegovina ',
          'abreviacion' =>'',
          'code_telefono' => '+387',
          'code' => '0028',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Botswana',
          'abreviacion' =>'',
          'code_telefono' => '+267',
          'code' => '0029',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Brazil ',
          'abreviacion' =>'',
          'code_telefono' => '+55',
          'code' => '0030',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Brunei',
          'abreviacion' =>'',
          'code_telefono' => '+673',
          'code' => '0031',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Bulgaria ',
          'abreviacion' =>'',
          'code_telefono' => '+359',
          'code' => '0032',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Burkina Faso',
          'abreviacion' =>'',
          'code_telefono' => '+226',
          'code' => '0033',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Burundi',
          'abreviacion' =>'',
          'code_telefono' => '+257',
          'code' => '0034',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Cambodia Kingdom of',
          'abreviacion' =>'',
          'code_telefono' => '+855',
          'code' => '0035',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Cameroon',
          'abreviacion' =>'',
          'code_telefono' => '+237',
          'code' => '0036',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Canada ',
          'abreviacion' =>'',
          'code_telefono' => '+1',
          'code' => '0037',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Cape Verde ',
          'abreviacion' =>'',
          'code_telefono' => '+238',
          'code' => '0038',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Cayman Islands ',
          'abreviacion' =>'',
          'code_telefono' => '+1-345',
          'code' => '0039',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Central African Republic ',
          'abreviacion' =>'',
          'code_telefono' => '+236',
          'code' => '0040',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Chad ',
          'abreviacion' =>'',
          'code_telefono' => '+235',
          'code' => '0041',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Chile ',
          'abreviacion' =>'',
          'code_telefono' => '+56',
          'code' => '0042',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'China ',
          'abreviacion' =>'',
          'code_telefono' => '+86',
          'code' => '0043',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Christmas Island ',
          'abreviacion' =>'',
          'code_telefono' => '+53',
          'code' => '0044',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Cocos Islands ',
          'abreviacion' =>'',
          'code_telefono' => '+61',
          'code' => '0045',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Colombia ',
          'abreviacion' =>'',
          'code_telefono' => '+57',
          'code' => '0046',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Comoros Union of the ',
          'abreviacion' =>'',
          'code_telefono' => '+269',
          'code' => '0047',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Congo Democratic Republic of the',
          'abreviacion' =>'',
          'code_telefono' => '+243',
          'code' => '0048',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Congo Republic of the',
          'abreviacion' =>'',
          'code_telefono' => '+242',
          'code' => '0049',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Cook Islands',
          'abreviacion' =>'',
          'code_telefono' => '+682',
          'code' => '0050',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Costa Rica ',
          'abreviacion' =>'',
          'code_telefono' => '+506',
          'code' => '0051',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Cote DIvoire',
          'abreviacion' =>'',
          'code_telefono' => '+225',
          'code' => '0052',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Croatia',
          'abreviacion' =>'',
          'code_telefono' => '+385',
          'code' => '0053',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Cuba ',
          'abreviacion' =>'',
          'code_telefono' => '+53',
          'code' => '0054',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Cyprus ',
          'abreviacion' =>'',
          'code_telefono' => '+357',
          'code' => '0055',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Czech Republic',
          'abreviacion' =>'',
          'code_telefono' => '+420',
          'code' => '0056',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Denmark ',
          'abreviacion' =>'',
          'code_telefono' => '+45',
          'code' => '0057',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Djibouti',
          'abreviacion' =>'',
          'code_telefono' => '+253',
          'code' => '0058',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Dominica ',
          'abreviacion' =>'',
          'code_telefono' => '+1-767',
          'code' => '0059',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Dominican Republic ',
          'abreviacion' =>'',
          'code_telefono' => '+1-809',
          'code' => '0060',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Dominican Republic ',
          'abreviacion' =>'',
          'code_telefono' => '+1-829',
          'code' => '0061',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'East Timor',
          'abreviacion' =>'',
          'code_telefono' => '+670',
          'code' => '0062',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Ecuador ',
          'abreviacion' =>'',
          'code_telefono' => '+593 ',
          'code' => '0063',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Egypt',
          'abreviacion' =>'',
          'code_telefono' => '+20',
          'code' => '0064',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'El Salvador ',
          'abreviacion' =>'',
          'code_telefono' => '+503',
          'code' => '0065',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Equatorial Guinea ',
          'abreviacion' =>'',
          'code_telefono' => '+240',
          'code' => '0066',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Eritrea ',
          'abreviacion' =>'',
          'code_telefono' => '+291',
          'code' => '0067',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Estonia ',
          'abreviacion' =>'',
          'code_telefono' => '+372',
          'code' => '0068',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Ethiopia ',
          'abreviacion' =>'',
          'code_telefono' => '+251',
          'code' => '0069',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Falkland Islands ',
          'abreviacion' =>'',
          'code_telefono' => '+500',
          'code' => '0070',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Faroe Islands ',
          'abreviacion' =>'',
          'code_telefono' => '+298',
          'code' => '0071',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Fiji ',
          'abreviacion' =>'',
          'code_telefono' => '+679',
          'code' => '0072',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Finland ',
          'abreviacion' =>'',
          'code_telefono' => '+358',
          'code' => '0073',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'France ',
          'abreviacion' =>'',
          'code_telefono' => '+33',
          'code' => '0074',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'French Guiana or French Guyana ',
          'abreviacion' =>'',
          'code_telefono' => '+594',
          'code' => '0075',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'French Polynesia ',
          'abreviacion' =>'',
          'code_telefono' => '+689',
          'code' => '0076',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Gabon ',
          'abreviacion' =>'',
          'code_telefono' => '+241',
          'code' => '0077',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Gambia The ',
          'abreviacion' =>'',
          'code_telefono' => '+220',
          'code' => '0078',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Georgia ',
          'abreviacion' =>'',
          'code_telefono' => '+995',
          'code' => '0079',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Germany ',
          'abreviacion' =>'',
          'code_telefono' => '+49',
          'code' => '0080',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Ghana ',
          'abreviacion' =>'',
          'code_telefono' => '+233',
          'code' => '0081',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Gibraltar ',
          'abreviacion' =>'',
          'code_telefono' => '+350',
          'code' => '0082',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Greece ',
          'abreviacion' =>'',
          'code_telefono' => '+30',
          'code' => '0083',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Greenland ',
          'abreviacion' =>'',
          'code_telefono' => '+299',
          'code' => '0084',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Grenada ',
          'abreviacion' =>'',
          'code_telefono' => '+1-473',
          'code' => '0085',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Guadeloupe',
          'abreviacion' =>'',
          'code_telefono' => '+590',
          'code' => '0086',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Guam',
          'abreviacion' =>'',
          'code_telefono' => '+1-671',
          'code' => '0087',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Guatemala ',
          'abreviacion' =>'',
          'code_telefono' => '+502',
          'code' => '0088',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Guinea ',
          'abreviacion' =>'',
          'code_telefono' => '+224',
          'code' => '0089',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Guinea-Bissau ',
          'abreviacion' =>'',
          'code_telefono' => '+245',
          'code' => '0090',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Guyana ',
          'abreviacion' =>'',
          'code_telefono' => '+592',
          'code' => '0091',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Haiti ',
          'abreviacion' =>'',
          'code_telefono' => '+509',
          'code' => '0092',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Honduras ',
          'abreviacion' =>'',
          'code_telefono' => '+504',
          'code' => '0093',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Hong Kong ',
          'abreviacion' =>'',
          'code_telefono' => '+852',
          'code' => '0094',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Hungary ',
          'abreviacion' =>'',
          'code_telefono' => '+36',
          'code' => '0095',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Iceland ',
          'abreviacion' =>'',
          'code_telefono' => '+354',
          'code' => '0096',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'India ',
          'abreviacion' =>'',
          'code_telefono' => '+91',
          'code' => '0097',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Indonesia ',
          'abreviacion' =>'',
          'code_telefono' => '+62',
          'code' => '0098',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Iran Islamic Republic of',
          'abreviacion' =>'',
          'code_telefono' => '+98',
          'code' => '0099',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Iraq ',
          'abreviacion' =>'',
          'code_telefono' => '+964',
          'code' => '0100',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Ireland ',
          'abreviacion' =>'',
          'code_telefono' => '+353',
          'code' => '0101',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Israel ',
          'abreviacion' =>'',
          'code_telefono' => '+972',
          'code' => '0102',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Italy ',
          'abreviacion' =>'',
          'code_telefono' => '+39',
          'code' => '0103',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Jamaica ',
          'abreviacion' =>'',
          'code_telefono' => '+1-876',
          'code' => '0104',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Japan ',
          'abreviacion' =>'',
          'code_telefono' => '+81',
          'code' => '0105',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Jordan ',
          'abreviacion' =>'',
          'code_telefono' => '+962',
          'code' => '0106',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Kazakstan',
          'abreviacion' =>'',
          'code_telefono' => '+7',
          'code' => '0107',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Kenya ',
          'abreviacion' =>'',
          'code_telefono' => '+254',
          'code' => '0108',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Kiribati ',
          'abreviacion' =>'',
          'code_telefono' => '+686',
          'code' => '0109',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Korea Democratic People Republic of ',
          'abreviacion' =>'',
          'code_telefono' => '+850',
          'code' => '0110',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Korea Republic of ',
          'abreviacion' =>'',
          'code_telefono' => '+82',
          'code' => '0111',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Kuwait ',
          'abreviacion' =>'',
          'code_telefono' => '+965',
          'code' => '0112',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Kyrgyzstan ',
          'abreviacion' =>'',
          'code_telefono' => '+996',
          'code' => '0113',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Lao People Democratic Republic ',
          'abreviacion' =>'',
          'code_telefono' => '+856',
          'code' => '0114',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Latvia ',
          'abreviacion' =>'',
          'code_telefono' => '+371',
          'code' => '0115',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Lebanon ',
          'abreviacion' =>'',
          'code_telefono' => '+961',
          'code' => '0116',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Lesotho ',
          'abreviacion' =>'',
          'code_telefono' => '+266',
          'code' => '0117',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Liberia ',
          'abreviacion' =>'',
          'code_telefono' => '+231',
          'code' => '0118',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Libya ',
          'abreviacion' =>'',
          'code_telefono' => '+218',
          'code' => '0119',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Liechtenstein ',
          'abreviacion' =>'',
          'code_telefono' => '+423',
          'code' => '0120',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Lithuania ',
          'abreviacion' =>'',
          'code_telefono' => '+370',
          'code' => '0121',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Luxembourg ',
          'abreviacion' =>'',
          'code_telefono' => '+352',
          'code' => '0122',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Macau ',
          'abreviacion' =>'',
          'code_telefono' => '+853',
          'code' => '0123',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Macedonia The Former Yugoslav Republic of',
          'abreviacion' =>'',
          'code_telefono' => '+389',
          'code' => '0124',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Madagascar ',
          'abreviacion' =>'',
          'code_telefono' => '+261',
          'code' => '0125',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Malawi ',
          'abreviacion' =>'',
          'code_telefono' => '+265',
          'code' => '0126',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Malaysia ',
          'abreviacion' =>'',
          'code_telefono' => '+60',
          'code' => '0127',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Maldives ',
          'abreviacion' =>'',
          'code_telefono' => '+960',
          'code' => '0128',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Mali ',
          'abreviacion' =>'',
          'code_telefono' => '+223',
          'code' => '0129',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Malta ',
          'abreviacion' =>'',
          'code_telefono' => '+356',
          'code' => '0130',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Marshall Islands ',
          'abreviacion' =>'',
          'code_telefono' => '+692',
          'code' => '0131',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Martinique ',
          'abreviacion' =>'',
          'code_telefono' => '+596',
          'code' => '0132',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Mauritania ',
          'abreviacion' =>'',
          'code_telefono' => '+222',
          'code' => '0133',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Mauritius ',
          'abreviacion' =>'',
          'code_telefono' => '+230',
          'code' => '0134',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Mayotte ',
          'abreviacion' =>'',
          'code_telefono' => '+269',
          'code' => '0135',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Mexico ',
          'abreviacion' =>'',
          'code_telefono' => '+52',
          'code' => '0136',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Micronesia Federated States of ',
          'abreviacion' =>'',
          'code_telefono' => '+691',
          'code' => '0137',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Moldova Republic of',
          'abreviacion' =>'',
          'code_telefono' => '+373',
          'code' => '0138',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Monaco Principality of',
          'abreviacion' =>'',
          'code_telefono' => '+377',
          'code' => '0139',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Mongolia ',
          'abreviacion' =>'',
          'code_telefono' => '+976',
          'code' => '0140',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Montserrat ',
          'abreviacion' =>'',
          'code_telefono' => '+1-664',
          'code' => '0141',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Morocco ',
          'abreviacion' =>'',
          'code_telefono' => '+212',
          'code' => '0142',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Mozambique ',
          'abreviacion' =>'',
          'code_telefono' => '+258',
          'code' => '0143',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Myanmar Union of ',
          'abreviacion' =>'',
          'code_telefono' => '+95',
          'code' => '0144',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Namibia ',
          'abreviacion' =>'',
          'code_telefono' => '+264',
          'code' => '0145',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Nauru ',
          'abreviacion' =>'',
          'code_telefono' => '+674',
          'code' => '0146',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Nepal ',
          'abreviacion' =>'',
          'code_telefono' => '+977',
          'code' => '0147',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Netherlands ',
          'abreviacion' =>'',
          'code_telefono' => '+31',
          'code' => '0148',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Netherlands Antilles ',
          'abreviacion' =>'',
          'code_telefono' => '+599',
          'code' => '0149',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'New Caledonia ',
          'abreviacion' =>'',
          'code_telefono' => '+687',
          'code' => '0150',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'New Zealand ',
          'abreviacion' =>'',
          'code_telefono' => '+64',
          'code' => '0151',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Nicaragua ',
          'abreviacion' =>'',
          'code_telefono' => '+505',
          'code' => '0152',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Niger ',
          'abreviacion' =>'',
          'code_telefono' => '+227',
          'code' => '0153',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Nigeria ',
          'abreviacion' =>'',
          'code_telefono' => '+234',
          'code' => '0154',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Niue ',
          'abreviacion' =>'',
          'code_telefono' => '+683',
          'code' => '0155',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Norfolk Island ',
          'abreviacion' =>'',
          'code_telefono' => '+672',
          'code' => '0156',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Northern Mariana Islands ',
          'abreviacion' =>'',
          'code_telefono' => '+1-670',
          'code' => '0157',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Norway ',
          'abreviacion' =>'',
          'code_telefono' => '+47',
          'code' => '0158',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Oman Sultanate of ',
          'abreviacion' =>'',
          'code_telefono' => '+968',
          'code' => '0159',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Pakistan ',
          'abreviacion' =>'',
          'code_telefono' => '+92',
          'code' => '0160',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Palau ',
          'abreviacion' =>'',
          'code_telefono' => '+680',
          'code' => '0161',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Palestinian State ',
          'abreviacion' =>'',
          'code_telefono' => '+970',
          'code' => '0162',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Panama ',
          'abreviacion' =>'',
          'code_telefono' => '+507',
          'code' => '0163',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Papua New Guinea ',
          'abreviacion' =>'',
          'code_telefono' => '+675',
          'code' => '0164',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Paraguay ',
          'abreviacion' =>'',
          'code_telefono' => '+595',
          'code' => '0165',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Peru ',
          'abreviacion' =>'',
          'code_telefono' => '+51',
          'code' => '0166',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Philippines ',
          'abreviacion' =>'',
          'code_telefono' => '+63',
          'code' => '0167',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Poland ',
          'abreviacion' =>'',
          'code_telefono' => '+48',
          'code' => '0168',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Portugal ',
          'abreviacion' =>'',
          'code_telefono' => '+351',
          'code' => '0169',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Puerto Rico ',
          'abreviacion' =>'',
          'code_telefono' => '+1-787',
          'code' => '0170',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Puerto Rico ',
          'abreviacion' =>'',
          'code_telefono' => '+1-939',
          'code' => '0171',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Qatar State of ',
          'abreviacion' =>'',
          'code_telefono' => '+974 ',
          'code' => '0172',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Reunion ',
          'abreviacion' =>'',
          'code_telefono' => '+262',
          'code' => '0173',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Romania ',
          'abreviacion' =>'',
          'code_telefono' => '+40',
          'code' => '0174',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Russian Federation ',
          'abreviacion' =>'',
          'code_telefono' => '+7',
          'code' => '0175',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Rwanda ',
          'abreviacion' =>'',
          'code_telefono' => '+250',
          'code' => '0176',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Saint Helena ',
          'abreviacion' =>'',
          'code_telefono' => '+290',
          'code' => '0177',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Saint Kitts and Nevis ',
          'abreviacion' =>'',
          'code_telefono' => '+1-869',
          'code' => '0178',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Saint Lucia ',
          'abreviacion' =>'',
          'code_telefono' => '+1-758',
          'code' => '0179',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Saint Pierre and Miquelon ',
          'abreviacion' =>'',
          'code_telefono' => '+508',
          'code' => '0180',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Saint Vincent and the Grenadines ',
          'abreviacion' =>'',
          'code_telefono' => '+1-784',
          'code' => '0181',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Samoa ',
          'abreviacion' =>'',
          'code_telefono' => '+685',
          'code' => '0182',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'San Marino ',
          'abreviacion' =>'',
          'code_telefono' => '+378',
          'code' => '0183',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Sao Tome and Principe ',
          'abreviacion' =>'',
          'code_telefono' => '+239',
          'code' => '0184',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Saudi Arabia ',
          'abreviacion' =>'',
          'code_telefono' => '+966',
          'code' => '0185',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Senegal ',
          'abreviacion' =>'',
          'code_telefono' => '+221',
          'code' => '0186',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Seychelles ',
          'abreviacion' =>'',
          'code_telefono' => '+248',
          'code' => '0187',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Sierra Leone ',
          'abreviacion' =>'',
          'code_telefono' => '+232',
          'code' => '0188',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Singapore ',
          'abreviacion' =>'',
          'code_telefono' => '+65',
          'code' => '0189',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Slovakia',
          'abreviacion' =>'',
          'code_telefono' => '+421',
          'code' => '0190',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Slovenia ',
          'abreviacion' =>'',
          'code_telefono' => '+386',
          'code' => '0191',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Solomon Islands ',
          'abreviacion' =>'',
          'code_telefono' => '+677',
          'code' => '0192',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Somalia ',
          'abreviacion' =>'',
          'code_telefono' => '+252',
          'code' => '0193',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'South Africa ',
          'abreviacion' =>'',
          'code_telefono' => '+27',
          'code' => '0194',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Spain ',
          'abreviacion' =>'',
          'code_telefono' => '+34',
          'code' => '0195',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Sri Lanka ',
          'abreviacion' =>'',
          'code_telefono' => '+94',
          'code' => '0196',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Sudan ',
          'abreviacion' =>'',
          'code_telefono' => '+249',
          'code' => '0197',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Suriname ',
          'abreviacion' =>'',
          'code_telefono' => '+597',
          'code' => '0198',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Swaziland Kingdom of ',
          'abreviacion' =>'',
          'code_telefono' => '+268',
          'code' => '0199',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Sweden ',
          'abreviacion' =>'',
          'code_telefono' => '+46',
          'code' => '0200',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Switzerland ',
          'abreviacion' =>'',
          'code_telefono' => '+41',
          'code' => '0201',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Syria ',
          'abreviacion' =>'',
          'code_telefono' => '+963',
          'code' => '0202',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Taiwan ',
          'abreviacion' =>'',
          'code_telefono' => '+886',
          'code' => '0203',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Tajikistan ',
          'abreviacion' =>'',
          'code_telefono' => '+992',
          'code' => '0204',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Tanzania United Republic of ',
          'abreviacion' =>'',
          'code_telefono' => '+255',
          'code' => '0205',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Thailand ',
          'abreviacion' =>'',
          'code_telefono' => '+66',
          'code' => '0206',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Tokelau ',
          'abreviacion' =>'',
          'code_telefono' => '+690',
          'code' => '0207',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Tonga Kingdom of ',
          'abreviacion' =>'',
          'code_telefono' => '+676',
          'code' => '0208',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Trinidad and Tobago ',
          'abreviacion' =>'',
          'code_telefono' => '+1-868',
          'code' => '0209',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Tunisia ',
          'abreviacion' =>'',
          'code_telefono' => '+216',
          'code' => '0210',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Turkey ',
          'abreviacion' =>'',
          'code_telefono' => '+90',
          'code' => '0211',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Turkmenistan ',
          'abreviacion' =>'',
          'code_telefono' => '+993',
          'code' => '0212',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Turks and Caicos Islands ',
          'abreviacion' =>'',
          'code_telefono' => '+1-649',
          'code' => '0213',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Tuvalu ',
          'abreviacion' =>'',
          'code_telefono' => '+688',
          'code' => '0214',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Uganda Republic of',
          'abreviacion' =>'',
          'code_telefono' => '+256',
          'code' => '0215',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Ukraine ',
          'abreviacion' =>'',
          'code_telefono' => '+380',
          'code' => '0216',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'United Arab Emirates ',
          'abreviacion' =>'',
          'code_telefono' => '+971',
          'code' => '0217',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'United Kingdom ',
          'abreviacion' =>'',
          'code_telefono' => '+44',
          'code' => '0218',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'United States ',
          'abreviacion' =>'',
          'code_telefono' => '+1',
          'code' => '0219',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Uruguay Oriental Republic of ',
          'abreviacion' =>'',
          'code_telefono' => '+598',
          'code' => '0220',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Uzbekistan ',
          'abreviacion' =>'',
          'code_telefono' => '+998',
          'code' => '0221',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Vanuatu ',
          'abreviacion' =>'',
          'code_telefono' => '+678',
          'code' => '0222',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Vatican City State ',
          'abreviacion' =>'',
          'code_telefono' => '+418',
          'code' => '0223',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Vietnam ',
          'abreviacion' =>'',
          'code_telefono' => '+84',
          'code' => '0224',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Virgin Islands British ',
          'abreviacion' =>'',
          'code_telefono' => '+1-284',
          'code' => '0225',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Virgin Islands United States ',
          'abreviacion' =>'',
          'code_telefono' => '+1-340',
          'code' => '0226',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Wallis and Futuna Islands ',
          'abreviacion' =>'',
          'code_telefono' => '+681',
          'code' => '0227',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Yemen ',
          'abreviacion' =>'',
          'code_telefono' => '+967',
          'code' => '0228',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Zambia Republic of ',
          'abreviacion' =>'',
          'code_telefono' => '+260',
          'code' => '0229',
          'default' => 0,
          ],
          [
          'nombre_pais' =>'Zimbabwe Republic of ',
          'abreviacion' =>'',
          'code_telefono' => '+263',
          'code' => '0230',
          'default' => 0,
          ]

        ]);

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('pais');
    }
}
